version: '3'
services:
  simplescan:
    image: nextier/simplescan:latest
    ports:
      - "5000:5000"
    volumes:
      - ./scans:/app/scans
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  
volumes:
  simplescan:

